//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int Total_Price { get; set; }
    }
}
